repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        -   id: check-case-conflict
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: requirements-txt-fixer
        -   id: trailing-whitespace
        -   id: check-added-large-files
        -   id: debug-statements

-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: bash -c 'make isort'
        language: system
        require_serial: true
    -   id: black
        name: black
        entry: bash -c 'make black'
        language: system
        require_serial: true
    -   id: flake8
        name: flake8
        entry: bash -c 'make flake8'
        language: system
        require_serial: true
    -   id: mypy
        name: mypy
        entry: bash -c 'make mypy'
        language: system
        require_serial: true
    -   id: frontcheck
        name: frontcheck
        entry: bash -c 'make frontcheck'
        language: system
        require_serial: true
