# This docker-compose file is designed for development purposes only

version: "3.8"

services:
  psql:
    container_name: db
    restart: always
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  django:
    container_name: backend
    build:
      context: ./recommendations-be
    command: sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./recommendations-be:/app
    depends_on:
      - psql

  react:
    container_name: frontend
    build:
      context: ./recommendations-fe
    ports:
      - "3000:3000"
    volumes:
      - ./recommendations-fe:/app
      - /app/node_modules

volumes:
  postgres_data:
