version: "3.8"

services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_DB=${PSQL_NAME}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    ports:
      - 5432:5432

  django:
    container_name: backend
    build:
      context: ./recommendations-be
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./recommendations-be:/backend
    depends_on:
      - psql

  react:
    container_name: frontend
    build:
      context: ./recommendations-fe
    ports:
      - 3000:3000
    volumes:
      - ./recommendations-fe/src:/frontend/src
