version: '3'

services:
  backend:
    build:
      context: ./recommendations-be
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --timeout 0
    ports:
      - "8000:8000"
#    volumes:
#      - static:/django/backend/static
  frontend:
    build:
      context: ./recommendations-fe
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
#      - static:/django/backend/static
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
#  static:
