version: "3.8"

services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=project_database
      - POSTGRES_USER=databaseadmin
      - POSTGRES_PASSWORD=Admin-123

  django:
    container_name: backend
    build:
      context: ./recommendations-be
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./recommendations-be:/backend
    depends_on:
      - psql

  react:
    container_name: frontend
    build:
      context: ./recommendations-fe
    ports:
      - 3000:3000
    volumes:
      - ./recommendations-fe/src:/frontend/src
