version: "3.8"

services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin-123

  django:
    container_name: recommendations-be
    build:
      context: ./recommendations-be
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./recommendations-be:/recommendations-be
    depends_on:
      - psql

  react:
    container_name: recommendations-fe
    build:
      context: ./recommendations-fe
    ports:
      - 3000:3000
    volumes:
      - ./recommendations-fe/src:/recommendations-fe/src
